;;; color-theme-sanityinc-tomorrow-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from color-theme-sanityinc-tomorrow.el

(when (boundp 'custom-theme-load-path) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(autoload 'color-theme-sanityinc-tomorrow-night "color-theme-sanityinc-tomorrow" "\
Apply the tomorrow night theme." t)
(autoload 'color-theme-sanityinc-tomorrow-day "color-theme-sanityinc-tomorrow" "\
Apply the tomorrow day theme." t)
(autoload 'color-theme-sanityinc-tomorrow-bright "color-theme-sanityinc-tomorrow" "\
Apply the tomorrow bright theme." t)
(autoload 'color-theme-sanityinc-tomorrow-eighties "color-theme-sanityinc-tomorrow" "\
Apply the tomorrow eighties theme." t)
(autoload 'color-theme-sanityinc-tomorrow-blue "color-theme-sanityinc-tomorrow" "\
Apply the tomorrow blue theme." t)
(register-definition-prefixes "color-theme-sanityinc-tomorrow" '("color-theme-sanityinc-tomorrow" "sanityinc-tomorrow--"))

;;; End of scraped data

(provide 'color-theme-sanityinc-tomorrow-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; color-theme-sanityinc-tomorrow-autoloads.el ends here
