dist: xenial
language: minimal
sudo: no
addons:
  apt:
    packages:
    - lua5.2
  homebrew:
    update: true
    packages:
    - lua
env:
  - EVM_EMACS=emacs-git-snapshot-travis-linux-xenial
  - EVM_EMACS=emacs-26.2-travis-linux-xenial
  - EVM_EMACS=emacs-26.1-travis-linux-xenial
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-24.5-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.3-travis
jobs:
  include:
    - os: osx
      env:
        - EVM_EMACS=emacs-26.1-travis
matrix:
  allow_failures:
    - env: EVM_EMACS=emacs-git-snapshot-travis-linux-xenial
  fast_finish: true
before_install:
  - source ./travis/before-install.sh
install:
  - cask install
script:
  - echo 'print(123)' | lua -i
  - make test
