name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.1
          - 25.3
          - 26.1
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - snapshot
        include:
          - emacs_version: 29.1
            target: deploy-manual
    steps:
    - uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v4
    - name: Install stack and ghc
      run: nix-env -iA stack ghc -f '<nixpkgs>'
    - name: Install texinfo
      if: matrix.target == 'deploy-manual'
      run: nix-env -iA texinfo -f '<nixpkgs>'
    - name: Run make
      run: make ${{ matrix.target || 'check' }}
      continue-on-error: ${{ matrix.emacs_version == 'snapshot' && (! matrix.target) }}
